config/routes.rb
FamComm::Application.routes.draw do
	resources :family_members
	resources :comm_events

	match "pictures" => "pictures#index"
	match "pictures/:pic_id" => "pictures#show"
	
	root :to => 'comm_events#index'
end

app/models/comm_event.rb
class CommEvent < ActiveRecord::Base
    attr_accessible :username, :subject, :body, :ts, :family_member_id
	belongs_to :family_member
end

app/models/family_member.rb
class FamilyMember < ActiveRecord::Base
	@room_name
  	attr_accessible :name, :room_id, :room_name
	has_many :comm_events
end

app/models/rooms.rb
class Rooms < ActiveRecord::Base
  # attr_accessible :title, :body
  #belongs_to :family_members
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comm_events_controller.rb
class CommEventsController < ApplicationController
  # GET /comm_events
  # GET /comm_events.json
  def index
    @comm_events = CommEvent.all.sort{|a,b| b.created_at <=> a.created_at }

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comm_events }
    end
  end

  # GET /comm_events/1
  # GET /comm_events/1.json
  def show
    @comm_event = CommEvent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comm_event }
    end
  end

  # GET /comm_events/new
  # GET /comm_events/new.json
  def new
    @comm_event = CommEvent.new
	@family_members = FamilyMember.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comm_event }
    end
  end

  # GET /comm_events/1/edit
  def edit
    @comm_event = CommEvent.find(params[:id])
  end

  # POST /comm_events
  # POST /comm_events.json
  def create
    @comm_event = CommEvent.new(params[:comm_event])
	@comm_event.ts = Time.new

	@family_members = FamilyMember.all

    respond_to do |format|
      if @comm_event.save
        format.html { redirect_to @comm_event, notice: 'Comm event was successfully created.' }
        format.json { render json: @comm_event, status: :created, location: @comm_event }
      else
        format.html { render action: "new" }
        format.json { render json: @comm_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comm_events/1
  # PUT /comm_events/1.json
  def update
    @comm_event = CommEvent.find(params[:id])

    respond_to do |format|
      if @comm_event.update_attributes(params[:comm_event])
        format.html { redirect_to @comm_event, notice: 'Comm event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comm_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comm_events/1
  # DELETE /comm_events/1.json
  def destroy
    @comm_event = CommEvent.find(params[:id])
    @comm_event.destroy

    respond_to do |format|
      format.html { redirect_to comm_events_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/family_members_controller.rb
class FamilyMembersController < ApplicationController
  # GET /family_members
  # GET /family_members.json
  def index
    @family_members = FamilyMember.all

	@family_members.each do |member|
		if(member.room_id != nil)
			if(FamComm::Application.config.rooms.has_key?( member.room_id ))
				member['room_name'] = FamComm::Application.config.rooms[member.room_id]['name']
			end
		end
	end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @family_members }
    end
  end

  # GET /family_members/1
  # GET /family_members/1.json
  def show
    @family_member = FamilyMember.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @family_member }
    end
  end

  # GET /family_members/new
  # GET /family_members/new.json
  def new
    @family_member = FamilyMember.new
	@rooms = FamComm::Application.config.rooms

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @family_member }
    end
  end

  # GET /family_members/1/edit
  def edit
    @family_member = FamilyMember.find(params[:id])
  end

  # POST /family_members
  # POST /family_members.json
  def create
    @family_member = FamilyMember.new(params[:family_member])

    respond_to do |format|
      if @family_member.save
        format.html { redirect_to @family_member, notice: 'Family member was successfully created.' }
        format.json { render json: @family_member, status: :created, location: @family_member }
      else
        format.html { render action: "new" }
        format.json { render json: @family_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /family_members/1
  # PUT /family_members/1.json
  def update
    @family_member = FamilyMember.find(params[:id])

    respond_to do |format|
      if @family_member.update_attributes(params[:family_member])
        format.html { redirect_to @family_member, notice: 'Family member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @family_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /family_members/1
  # DELETE /family_members/1.json
  def destroy
    @family_member = FamilyMember.find(params[:id])
    @family_member.destroy

    respond_to do |format|
      format.html { redirect_to family_members_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pictures_controller.rb
FS_PIC_ROOT = "/Users/bryankroger/Documents/Vacation_Cruise_2013"

class PicturesController < ApplicationController

	def index
		@pictures = Dir.glob( "%s/dolphin_adventure/*.JPG" % FS_PIC_ROOT )
		respond_to do |f|
			f.html
		end
	end

	def show
		@picture = "%s/dolphin_adventure/%s.%s" % [FS_PIC_ROOT,params[:pic_id],params[:format]]
		send_file( @picture )
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comm_events_helper.rb
module CommEventsHelper
end

app/helpers/family_members_helper.rb
module FamilyMembersHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/comm_events/_form.html.erb
<%= form_for(@comm_event) do |f| %>
  <% if @comm_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comm_event.errors.count, "error") %> prohibited this comm_event from being saved:</h2>

      <ul>
      <% @comm_event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<table cellspacing="0" cellpadding="0" style="width: 100%;">
	<tr>
		<td style="width: 100px;">Who are you?</td>
		<!-- <td><input style="width: 400px;" type="text" name="comm_event[username]" value="<%= @comm_event.username %>"></td> -->
		<td><select name="comm_event[family_member_id]"><% @family_members.each do |member| %>
			<option value="<%= member.id %>"><%= member.name %></option>
		<% end %></select></td>
	</tr><tr>
		<td>Subject:</td>
		<td><input style="width: 400px;" type="text" name="comm_event[subject]" value="<%= @comm_event.subject %>"></td>
	</tr><tr>
		<td>Body:</td>
		<td><textarea style="width: 400px; height: 100px;" name="comm_event[body]"><%= @comm_event.body %></textarea>
	</tr>
	</table>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comm_events/edit.html.erb
<h1>Editing comm_event</h1>

<%= render 'form' %>

<%= link_to 'Show', @comm_event %> |
<%= link_to 'Back', comm_events_path %>

app/views/comm_events/index.html.erb
<h1>The Clog ( Cruise Log )</h1>
<div style="padding-bottom: 20px;"> <%= link_to 'Say something awesome.', new_comm_event_path %> </div>
<div style="padding-bottom: 20px;"><a href="/pictures/" />Pictures</a></div> 

<table cellspacing="0" cellpadding="5" style="width: 100%;">
  <tr style="background-color: #217AD3; padding-top: 10px; color: #ffffff; text-align: left">
    <th></th>
	<!--
    <th></th>
    <th></th>
	-->
    <th>Created</th>
    <th>User</th>
    <th>Subject</th>
    <th>Body</th>
  </tr>

<% @comm_events.each do |comm_event| %>
  <tr>
    <td style="width: 50px;"><%= link_to 'Show', comm_event %></td>
	<!--
    <td style="width: 50px;"><%= link_to 'Edit', edit_comm_event_path(comm_event) %></td>
    <td style="width: 50px;"><%= link_to 'Destroy', comm_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	-->

  	<td style="width: 200px;"><%= comm_event.created_at %></td>
  	<td style="width: 100px;"><%= (comm_event.family_member != nil ? comm_event.family_member.name : comm_event.username ) %></td>

	<!-- <td style="width: 200px;"><%= (comm_event.subject.size > 20 ? "%s..." % comm_event.subject[0,17] : comm_event.subject ) %></td> -->
  	<td style="width: 200px;"><%= comm_event.subject %></td>

  	<td><%= (comm_event.body.size > 40 ? "%s..." % comm_event.body[0,37] : comm_event.body ) %></td>
  </tr>
<% end %>
</table>

<hr />
<br />

app/views/comm_events/new.html.erb
<h1>New comm_event</h1>

<%= render 'form' %>

<%= link_to 'Back to messages.', comm_events_path %>

app/views/comm_events/show.html.erb
<p id="notice"><%= notice %></p>

<h1>On <%= @comm_event.created_at %> <%= (@comm_event.family_member != nil ? @comm_event.family_member.name : @comm_event.username ) %> posted...</h1>

<div style="background-color: #217AD3; padding: 10px; color: #ffffff; text-align: center"><%= @comm_event.subject %></div>
<div style="padding: 10px;border: 1px solid #000000;"><%= @comm_event.body %></div>

<br/><br/>
<hr/>

<!--
<%= link_to 'Edit', edit_comm_event_path(@comm_event) %> |
-->
<%= link_to 'Back to messages.', comm_events_path %>

app/views/family_members/_form.html.erb
<%= form_for(@family_member) do |f| %>
  <% if @family_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@family_member.errors.count, "error") %> prohibited this family_member from being saved:</h2>

      <ul>
      <% @family_member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<table cellspacing="0" cellpadding="0" style="width: 100%;">
	<tr>
		<td style="width: 33%;">Name:</td>
		<td><input style="width: 400px;" type="text" name="family_member[name]" value="<%= @family_member.name %>"></td>
	</tr><tr>
		<td>Room:</td>
		<td><select name="family_member[room_id]"><% @rooms.each do |room_id,room_info| %>
			<option value="<%= room_id %>"><%= room_info['name'] %></option>
		<% end %></select></td>
	</tr>
	</table>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/family_members/edit.html.erb
<h1>Editing family_member</h1>

<%= render 'form' %>

<%= link_to 'Show', @family_member %> |
<%= link_to 'Back', family_members_path %>

app/views/family_members/index.html.erb
<h1>Listing family_members</h1>

<%= link_to 'Create new family member.', new_family_member_path %>
<br/>
<br/>

<table cellspacing="0" cellpadding="5" style="width: 100%;">
  <tr style="background-color: #217AD3; padding-top: 10px; color: #ffffff; text-align: left">
  	<th>Name</th>
  	<th>Room</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @family_members.each do |family_member| %>
  <tr>
  	<td><%= family_member.name %></td>
  	<td><%= family_member['room_name'] %></td>
    <td><%= link_to 'Show', family_member %></td>
    <td><%= link_to 'Edit', edit_family_member_path(family_member) %></td>
    <td><%= link_to 'Destroy', family_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br/>
<hr/>
<%= link_to 'Back to messages.', comm_events_path %>

app/views/family_members/new.html.erb
<h1>New family_member</h1>

<%= render 'form' %>

<%= link_to 'Back', family_members_path %>

app/views/family_members/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_family_member_path(@family_member) %> |
<%= link_to 'Back', family_members_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FamComm</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pictures/index.html.erb
<h1>Pictures</h1>

<% @pictures.each do |pic| %>
  	<div><img height="200" src="/pictures/<%= File.basename( pic ) %>" /></div>
	<!--
  	<div><a href="/pictures/<%= File.basename( pic ) %>"><%= File.basename( pic ) %></a></div>
  	-->
<% end %>